version: '3.9'
services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/data/postgres
      - ./src/scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: pgweb
    restart: unless-stopped
    ports:
      - '8082:8081'
    environment:
      - PGWEB_DATABASE_URL=postgresql://username:password@postgres:5432/database?sslmode=disable
    depends_on:
      - postgres

  mongodb:
    image: mongo:7.0.2
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    volumes:
      - mongodb-data:/data/db
      - ./src/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_BASICAUTH_USERNAME=username
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_AUTH_DATABASE=database
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - VCAP_APP_PORT=8081
    depends_on:
      - mongodb
    ports:
      - '8081:8081'

volumes:
  postgres-data:
    driver: local
  mongodb-data:
    driver: local
