version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/data/postgres
      - ./src/scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    volumes:
      - mongodb-data:/data/db
      - ./src/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  postgres-data:
    driver: local
  mongodb-data:
    driver: local
